import "./globals.css";
import Navbar from '@/components/Navbar'
import { Parkinsans } from "next/font/google";

const parkinsans = Parkinsans({
  subsets: ["latin"],
  weight: ['300', '400', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={parkinsans.className}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
